# Pembacaan Data dari CSV

In [1]:
%cat contoh-data-data-mining.csv

Time,Age,Name,Sentiment
2017/3/14 8:34:48,41,Anton,negative
2017/10/5 9:56:51,31,Budi,positive
2018/6/15 14:28:5,22,Charlie,positive
2018/6/5 17:36:32,18,Dedi,positive
2018/9/25 7:46:23,12,Edy,negative
2019/7/4 20:11:33,43,Feris,positive
2017/11/24 8:58:27,49,Galah,negative
2019/12/14 15:15:41,13,Halimah,positive
2018/12/1 5:37:10,30,Intan,negative
2017/10/14 23:25:42,47,Jack,positive
2017/4/13 9:37:6,47,Kirun,positive
2019/3/13 12:43:35,29,Lala,positive
2019/8/14 17:32:8,18,Miftah,positive
2018/4/21 16:12:40,29,Nono,positive
2018/11/23 2:18:59,28,Ono,negative
2017/1/25 20:1:4,41,Pras,positive
2017/12/8 6:1:21,27,Qori,negative
2017/12/3 18:0:44,46,Raras,positive
2019/8/24 17:25:58,38,Smith,positive
2018/9/10 3:59:15,12,Tim,negative
2019/12/14 5:28:8,49,Uvwevwe,negative
2019/4/6 14:51:26,42,Victor,positive
2019/5/4 21:41:19,10,Wendy,positive
2019/2/28 11:56:35,18,Xavier,positive
2018/8/26 6:16:44,33,Yono,negative
2018/6/24 5:7:25,37,Zakir,negative
2019/7/7 11:25:7,18,Adinda,positive
2019/2/15 6:37:14,28,Beatrix,negative
2017/1/1 12:43:7,32,Corry,positive
2017/1/22 19:52:30,26,Dodit,positive
2017/10/1 23:51:53,28,Ega,positive
2018/11/4 4:48:58,25,Frans,negative
2018/1/18 5:52:47,19,Anton,negative
2017/12/23 14:28:21,43,Budi,positive
2018/11/14 5:57:18,15,Charlie,negative
2017/11/25 15:43:56,14,Dedi,positive
2018/1/2 4:29:59,50,Edy,negative
2018/11/21 6:39:48,26,Feris,negative
2018/10/14 8:50:6,38,Galah,negative
2017/5/7 23:32:47,49,Halimah,positive
2017/1/3 16:41:35,10,Intan,positive
2019/8/17 8:11:58,10,Jack,positive
2017/7/8 1:53:13,48,Kirun,negative
2019/2/18 4:7:52,37,Lala,negative
2018/7/26 21:37:35,10,Miftah,positive
2019/11/22 21:33:49,37,Nono,positive
2019/11/6 8:57:15,42,Ono,negative
2019/7/9 0:14:59,50,Pras,negative
2019/8/1 12:30:10,41,Qori,positive
2017/6/7 10:54:43,49,Raras,positive
2017/12/14 2:3:48,27,Smith,negative
2019/12/23 21:46:0,38,Tim,positive
2018/1/25 15:30:48,13,Uvwevwe,positive
2017/5/15 4:38:5,46,Victor,negative
2018/2/28 20:3:57,42,Wendy,positive
2019/3/22 18:14:21,28,Xavier,positive
2018/9/12 7:11:20,39,Yono,negative
2018/4/8 5:36:56,38,Zakir,negative
2018/11/25 8:1:58,31,Adinda,negative
2019/2/17 12:53:39,32,Beatrix,positive
2019/2/2 20:18:11,17,Corry,positive
2017/9/8 22:33:0,13,Dodit,positive
2019/8/7 3:53:41,16,Ega,negative
2017/4/21 9:21:52,33,Frans,positive
2019/4/14 18:50:46,45,Anton,positive
2017/10/19 21:56:0,45,Budi,positive
2017/2/13 13:19:20,35,Charlie,positive
2019/8/19 19:52:7,50,Dedi,positive
2017/1/11 19:46:9,36,Edy,positive
2017/8/25 14:42:22,30,Feris,positive
2018/6/4 3:11:55,17,Galah,negative
2017/10/2 6:15:35,46,Halimah,negative
2017/2/15 1:10:53,36,Intan,negative
2018/1/5 16:34:19,25,Jack,positive
2017/12/21 10:41:2,31,Kirun,positive
?/7/15 9:41:3,23,Lala,positive
2018/5/2 13:57:30,43,Miftah,positive
2018/1/20 23:40:31,44,Nono,positive
2018/2/27 23:23:20,21,Ono,positive
2018/8/12 21:?:20,11,Pras,positive
2017/1/26 5:6:5,29,Qori,negative
2019/12/11 10:55:16,41,Raras,positive
2018/4/9 4:30:48,50,Smith,negative
2018/5/10 5:9:27,?,Tim,negative
2019/4/27 4:39:34,16,Uvwevwe,negative
2018/6/26 7:2:57,36,Victor,negative
2018/9/6 4:42:59,13,Wendy,negative
2018/10/1 3:15:55,41,Xavier,?
2019/1/2 20:52:52,44,Yono,positive
2017/12/24 1:19:7,10,Zakir,negative
2018/2/6 13:47:11,37,Adinda,positive
2017/9/19 9:30:48,150,Beatrix,positive
2019/11/14 5:41:6,31,Corry,negative
2017/12/15 11:44:25,34,?,positive
2019/3/10 0:41:34,42,Ega,negative
2017/3/11 8:10:58,12,Frans,positive
2018/9/17 9:12:59,26,Anton,positive
2019/4/13 18:55:54,23,Budi,positive
2018/2/20 3:18:26,28,Charlie,negative
2017/4/23 13:53:6,20,Dedi,positive

## Pakai pandas

In [10]:
import pandas
df = pandas.read_csv('contoh-data-data-mining.csv')
print(df)

                   Time  Age     Name Sentiment
0     2017/3/14 8:34:48   41    Anton  negative
1     2017/10/5 9:56:51   31     Budi  positive
2     2018/6/15 14:28:5   22  Charlie  positive
3     2018/6/5 17:36:32   18     Dedi  positive
4     2018/9/25 7:46:23   12      Edy  negative
5     2019/7/4 20:11:33   43    Feris  positive
6    2017/11/24 8:58:27   49    Galah  negative
7   2019/12/14 15:15:41   13  Halimah  positive
8     2018/12/1 5:37:10   30    Intan  negative
9   2017/10/14 23:25:42   47     Jack  positive
10     2017/4/13 9:37:6   47    Kirun  positive
11   2019/3/13 12:43:35   29     Lala  positive
12    2019/8/14 17:32:8   18   Miftah  positive
13   2018/4/21 16:12:40   29     Nono  positive
14   2018/11/23 2:18:59   28      Ono  negative
15     2017/1/25 20:1:4   41     Pras  positive
16     2017/12/8 6:1:21   27     Qori  negative
17    2017/12/3 18:0:44   46    Raras  positive
18   2019/8/24 17:25:58   38    Smith  positive
19    2018/9/10 3:59:15   12      Tim  negative
20    2019/12/14 5:28:8   49  Uvwevwe  negative
21    2019/4/6 14:51:26   42   Victor  positive
22    2019/5/4 21:41:19   10    Wendy  positive
23   2019/2/28 11:56:35   18   Xavier  positive
24    2018/8/26 6:16:44   33     Yono  negative
25     2018/6/24 5:7:25   37    Zakir  negative
26     2019/7/7 11:25:7   18   Adinda  positive
27    2019/2/15 6:37:14   28  Beatrix  negative
28     2017/1/1 12:43:7   32    Corry  positive
29   2017/1/22 19:52:30   26    Dodit  positive
..                  ...  ...      ...       ...
70     2018/6/4 3:11:55   17    Galah  negative
71    2017/10/2 6:15:35   46  Halimah  negative
72    2017/2/15 1:10:53   36    Intan  negative
73    2018/1/5 16:34:19   25     Jack  positive
74   2017/12/21 10:41:2   31    Kirun  positive
75        ?/7/15 9:41:3   23     Lala  positive
76    2018/5/2 13:57:30   43   Miftah  positive
77   2018/1/20 23:40:31   44     Nono  positive
78   2018/2/27 23:23:20   21      Ono  positive
79    2018/8/12 21:?:20   11     Pras  positive
80      2017/1/26 5:6:5   29     Qori  negative
81  2019/12/11 10:55:16   41    Raras  positive
82     2018/4/9 4:30:48   50    Smith  negative
83     2018/5/10 5:9:27    ?      Tim  negative
84    2019/4/27 4:39:34   16  Uvwevwe  negative
85     2018/6/26 7:2:57   36   Victor  negative
86     2018/9/6 4:42:59   13    Wendy  negative
87    2018/10/1 3:15:55   41   Xavier         ?
88    2019/1/2 20:52:52   44     Yono  positive
89    2017/12/24 1:19:7   10    Zakir  negative
90    2018/2/6 13:47:11   37   Adinda  positive
91    2017/9/19 9:30:48  150  Beatrix  positive
92    2019/11/14 5:41:6   31    Corry  negative
93  2017/12/15 11:44:25   34        ?  positive
94    2019/3/10 0:41:34   42      Ega  negative
95    2017/3/11 8:10:58   12    Frans  positive
96    2018/9/17 9:12:59   26    Anton  positive
97   2019/4/13 18:55:54   23     Budi  positive
98    2018/2/20 3:18:26   28  Charlie  negative
99    2017/4/23 13:53:6   20     Dedi  positive

[100 rows x 4 columns]

In [11]:
print(df.columns)
print(df.Age)

Index(['Time', 'Age', 'Name', 'Sentiment'], dtype='object')
0      41
1      31
2      22
3      18
4      12
5      43
6      49
7      13
8      30
9      47
10     47
11     29
12     18
13     29
14     28
15     41
16     27
17     46
18     38
19     12
20     49
21     42
22     10
23     18
24     33
25     37
26     18
27     28
28     32
29     26
     ...
70     17
71     46
72     36
73     25
74     31
75     23
76     43
77     44
78     21
79     11
80     29
81     41
82     50
83      ?
84     16
85     36
86     13
87     41
88     44
89     10
90     37
91    150
92     31
93     34
94     42
95     12
96     26
97     23
98     28
99     20
Name: Age, Length: 100, dtype: object

In [12]:
df.Time.str.split(' ').apply(lambda x: x[0])

0      2017/3/14
1      2017/10/5
2      2018/6/15
3       2018/6/5
4      2018/9/25
5       2019/7/4
6     2017/11/24
7     2019/12/14
8      2018/12/1
9     2017/10/14
10     2017/4/13
11     2019/3/13
12     2019/8/14
13     2018/4/21
14    2018/11/23
15     2017/1/25
16     2017/12/8
17     2017/12/3
18     2019/8/24
19     2018/9/10
20    2019/12/14
21      2019/4/6
22      2019/5/4
23     2019/2/28
24     2018/8/26
25     2018/6/24
26      2019/7/7
27     2019/2/15
28      2017/1/1
29     2017/1/22
         ...
70      2018/6/4
71     2017/10/2
72     2017/2/15
73      2018/1/5
74    2017/12/21
75        ?/7/15
76      2018/5/2
77     2018/1/20
78     2018/2/27
79     2018/8/12
80     2017/1/26
81    2019/12/11
82      2018/4/9
83     2018/5/10
84     2019/4/27
85     2018/6/26
86      2018/9/6
87     2018/10/1
88      2019/1/2
89    2017/12/24
90      2018/2/6
91     2017/9/19
92    2019/11/14
93    2017/12/15
94     2019/3/10
95     2017/3/11
96     2018/9/17
97     2019/4/13
98     2018/2/20
99     2017/4/23
Name: Time, Length: 100, dtype: object

In [17]:
df['dateOnly'] = df.Time.str.split(' ').apply(lambda x: x[0])
df['yearOnly'] = df.Time.str.split(' ').apply(lambda x: x[0].split('/')[0])
df['yearOnlyClean'] = df.Time.str.split(' ').apply(lambda x: x[0].split('/')[0])
df

                   Time  Age     Name Sentiment    dateOnly yearOnly
0     2017/3/14 8:34:48   41    Anton  negative   2017/3/14     2017
1     2017/10/5 9:56:51   31     Budi  positive   2017/10/5     2017
2     2018/6/15 14:28:5   22  Charlie  positive   2018/6/15     2018
3     2018/6/5 17:36:32   18     Dedi  positive    2018/6/5     2018
4     2018/9/25 7:46:23   12      Edy  negative   2018/9/25     2018
5     2019/7/4 20:11:33   43    Feris  positive    2019/7/4     2019
6    2017/11/24 8:58:27   49    Galah  negative  2017/11/24     2017
7   2019/12/14 15:15:41   13  Halimah  positive  2019/12/14     2019
8     2018/12/1 5:37:10   30    Intan  negative   2018/12/1     2018
9   2017/10/14 23:25:42   47     Jack  positive  2017/10/14     2017
10     2017/4/13 9:37:6   47    Kirun  positive   2017/4/13     2017
11   2019/3/13 12:43:35   29     Lala  positive   2019/3/13     2019
12    2019/8/14 17:32:8   18   Miftah  positive   2019/8/14     2019
13   2018/4/21 16:12:40   29     Nono  positive   2018/4/21     2018
14   2018/11/23 2:18:59   28      Ono  negative  2018/11/23     2018
15     2017/1/25 20:1:4   41     Pras  positive   2017/1/25     2017
16     2017/12/8 6:1:21   27     Qori  negative   2017/12/8     2017
17    2017/12/3 18:0:44   46    Raras  positive   2017/12/3     2017
18   2019/8/24 17:25:58   38    Smith  positive   2019/8/24     2019
19    2018/9/10 3:59:15   12      Tim  negative   2018/9/10     2018
20    2019/12/14 5:28:8   49  Uvwevwe  negative  2019/12/14     2019
21    2019/4/6 14:51:26   42   Victor  positive    2019/4/6     2019
22    2019/5/4 21:41:19   10    Wendy  positive    2019/5/4     2019
23   2019/2/28 11:56:35   18   Xavier  positive   2019/2/28     2019
24    2018/8/26 6:16:44   33     Yono  negative   2018/8/26     2018
25     2018/6/24 5:7:25   37    Zakir  negative   2018/6/24     2018
26     2019/7/7 11:25:7   18   Adinda  positive    2019/7/7     2019
27    2019/2/15 6:37:14   28  Beatrix  negative   2019/2/15     2019
28     2017/1/1 12:43:7   32    Corry  positive    2017/1/1     2017
29   2017/1/22 19:52:30   26    Dodit  positive   2017/1/22     2017
..                  ...  ...      ...       ...         ...      ...
70     2018/6/4 3:11:55   17    Galah  negative    2018/6/4     2018
71    2017/10/2 6:15:35   46  Halimah  negative   2017/10/2     2017
72    2017/2/15 1:10:53   36    Intan  negative   2017/2/15     2017
73    2018/1/5 16:34:19   25     Jack  positive    2018/1/5     2018
74   2017/12/21 10:41:2   31    Kirun  positive  2017/12/21     2017
75        ?/7/15 9:41:3   23     Lala  positive      ?/7/15        ?
76    2018/5/2 13:57:30   43   Miftah  positive    2018/5/2     2018
77   2018/1/20 23:40:31   44     Nono  positive   2018/1/20     2018
78   2018/2/27 23:23:20   21      Ono  positive   2018/2/27     2018
79    2018/8/12 21:?:20   11     Pras  positive   2018/8/12     2018
80      2017/1/26 5:6:5   29     Qori  negative   2017/1/26     2017
81  2019/12/11 10:55:16   41    Raras  positive  2019/12/11     2019
82     2018/4/9 4:30:48   50    Smith  negative    2018/4/9     2018
83     2018/5/10 5:9:27    ?      Tim  negative   2018/5/10     2018
84    2019/4/27 4:39:34   16  Uvwevwe  negative   2019/4/27     2019
85     2018/6/26 7:2:57   36   Victor  negative   2018/6/26     2018
86     2018/9/6 4:42:59   13    Wendy  negative    2018/9/6     2018
87    2018/10/1 3:15:55   41   Xavier         ?   2018/10/1     2018
88    2019/1/2 20:52:52   44     Yono  positive    2019/1/2     2019
89    2017/12/24 1:19:7   10    Zakir  negative  2017/12/24     2017
90    2018/2/6 13:47:11   37   Adinda  positive    2018/2/6     2018
91    2017/9/19 9:30:48  150  Beatrix  positive   2017/9/19     2017
92    2019/11/14 5:41:6   31    Corry  negative  2019/11/14     2019
93  2017/12/15 11:44:25   34        ?  positive  2017/12/15     2017
94    2019/3/10 0:41:34   42      Ega  negative   2019/3/10     2019
95    2017/3/11 8:10:58   12    Frans  positive   2017/3/11     2017
96    2018/9/17 9:12:59   26    Anton  positive   2018/9/17     2018
97   2019/4/13 18:55:54   23     Budi  positive   2019/4/13     2019
98    2018/2/20 3:18:26   28  Charlie  negative   2018/2/20     2018
99    2017/4/23 13:53:6   20     Dedi  positive   2017/4/23     2017

[100 rows x 6 columns]